var DATA_SRC="./src/data/";
var DATA_FILE="./src/data.json";
var fs=require("fs");

var bigData={id:"com.agnibho.com.pdosage.data", timestamp: Date.now(), version: 0, dosage:[]};

if(process.argv[2]=="watch"){
    fs.watch(DATA_SRC, jsonCat);
}
else{
    jsonCat();
}

function jsonCat(){
    console.log("Joining JSON data files");
    var files=fs.readdirSync(DATA_SRC);
    for(var i=0; i<files.length; i++){
	if(files[i].indexOf(".")!==0){
	    try{
		bigData.dosage=bigData.dosage.concat(JSON.parse(fs.readFileSync(DATA_SRC+files[i], "utf8")));
	    }
	    catch(e){
		console.log(e);
	    }
	}
    }
    fs.writeFileSync(DATA_FILE, JSON.stringify(bigData), "utf8");
    console.log(DATA_FILE +" generated. Do not edit this file manually as it is overwritten on each build.");
}
